export const data= [{
    "id": 1,
    "first_name": "Sonny",
    "last_name": "Itzcak",
    "email": "sitzcak0@pagesperso-orange.fr",
    "gender": "Female"
  }, {
    "id": 2,
    "first_name": "Terence",
    "last_name": "Stanfield",
    "email": "tstanfield1@odnoklassniki.ru",
    "gender": "Male"
  }, {
    "id": 3,
    "first_name": "Rickey",
    "last_name": "Willder",
    "email": "rwillder2@weather.com",
    "gender": "Male"
  }, {
    "id": 4,
    "first_name": "Archy",
    "last_name": "Greschke",
    "email": "agreschke3@amazonaws.com",
    "gender": "Male"
  }, {
    "id": 5,
    "first_name": "Bearnard",
    "last_name": "Melendez",
    "email": "bmelendez4@diigo.com",
    "gender": "Genderqueer"
  }, {
    "id": 6,
    "first_name": "Glenn",
    "last_name": "Ricca",
    "email": "gricca5@cnbc.com",
    "gender": "Male"
  }, {
    "id": 7,
    "first_name": "Harper",
    "last_name": "Irwin",
    "email": "hirwin6@joomla.org",
    "gender": "Male"
  }, {
    "id": 8,
    "first_name": "Thebault",
    "last_name": "Craghead",
    "email": "tcraghead7@bbb.org",
    "gender": "Male"
  }, {
    "id": 9,
    "first_name": "Vaclav",
    "last_name": "Northgraves",
    "email": "vnorthgraves8@rakuten.co.jp",
    "gender": "Male"
  }, {
    "id": 10,
    "first_name": "Analiese",
    "last_name": "Blunkett",
    "email": "ablunkett9@squarespace.com",
    "gender": "Female"
  }, {
    "id": 11,
    "first_name": "Murdock",
    "last_name": "Dewitt",
    "email": "mdewitta@shareasale.com",
    "gender": "Male"
  }, {
    "id": 12,
    "first_name": "Mel",
    "last_name": "Lindborg",
    "email": "mlindborgb@amazon.co.uk",
    "gender": "Male"
  }, {
    "id": 13,
    "first_name": "Rollo",
    "last_name": "Bletcher",
    "email": "rbletcherc@wiley.com",
    "gender": "Male"
  }, {
    "id": 14,
    "first_name": "Grover",
    "last_name": "Lowson",
    "email": "glowsond@issuu.com",
    "gender": "Polygender"
  }, {
    "id": 15,
    "first_name": "Glenden",
    "last_name": "Stang-Gjertsen",
    "email": "gstanggjertsene@list-manage.com",
    "gender": "Male"
  }, {
    "id": 16,
    "first_name": "Nealson",
    "last_name": "Seage",
    "email": "nseagef@dot.gov",
    "gender": "Male"
  }, {
    "id": 17,
    "first_name": "Amerigo",
    "last_name": "Burdett",
    "email": "aburdettg@dot.gov",
    "gender": "Male"
  }, {
    "id": 18,
    "first_name": "Wain",
    "last_name": "Leahair",
    "email": "wleahairh@fotki.com",
    "gender": "Male"
  }, {
    "id": 19,
    "first_name": "Gualterio",
    "last_name": "Spatig",
    "email": "gspatigi@blog.com",
    "gender": "Agender"
  }, {
    "id": 20,
    "first_name": "Berne",
    "last_name": "Edler",
    "email": "bedlerj@friendfeed.com",
    "gender": "Male"
  }]
  